gp_index:
    pattern: /
    defaults: { _controller: GestionProjetBundle:Projet:index }
    options:
        expose: true

gp_accueil:
    pattern: /accueil
    defaults: { _controller: GestionProjetBundle:Default:accueil }
    options:
        expose: true
        
gp_projet_admin:
    pattern: /projets-admin
    defaults: { _controller: GestionProjetBundle:Projet:projet }
    options:
        expose: true

gp_projet_add:
    pattern: /add-projet
    defaults: { _controller: GestionProjetBundle:Projet:addprojet }
    options:
        expose: true
        
gp_projet_update:
    pattern: /update-projet
    defaults: { _controller: GestionProjetBundle:Projet:updateprojet }
    options:
        expose: true
        
gp_projet_get:
    pattern: /get-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:getprojet }
    options:
        expose: true

gp_projet_delete:
    pattern: /delete-projet/{id} 
    defaults: { _controller: GestionProjetBundle:Projet:deleteprojet }
    options:
        expose: true

gp_intervenant:
    pattern: /intervenants
    defaults: { _controller: GestionProjetBundle:Intervenants:intervenants }
    options:
        expose: true
        
gp_intervenant_add:
    pattern: /add-intervenant
    defaults: { _controller: GestionProjetBundle:Intervenant:addintervenant }
    options:
        expose: true

gp_intervenant_update:
    pattern: /update-intervenant
    defaults: { _controller: GestionProjetBundle:Intervenant:updateintervenant }
    options:
        expose: true
        
gp_intervenant_delete:
    pattern: /delete-intervenant
    defaults: { _controller: GestionProjetBundle:Intervenant:deleteintervenant }
    options:
        expose: true
        
gp_tache:
    pattern: /taches
    defaults: { _controller: GestionProjetBundle:Taches:taches }
    options:
        expose: true
        
gp_tache_add:
    pattern: /add-tache
    defaults: { _controller: GestionProjetBundle:Taches:addtache }
    options:
        expose: true

gp_tache_update:
    pattern: /update-tache
    defaults: { _controller: GestionProjetBundle:Taches:updatetache }
    options:
        expose: true
        
gp_tache_delete:
    pattern: /delete-tache
    defaults: { _controller: GestionProjetBundle:Taches:deletetache }
    options:
        expose: true
        
        
gp_lot:
    pattern: /lots
    defaults: { _controller: GestionProjetBundle:Lots:lots }
    options:
        expose: true
        
gp_lot_add:
    pattern: /add-lot
    defaults: { _controller: GestionProjetBundle:Lots:addlot }
    options:
        expose: true

gp_lot_update:
    pattern: /update-lot
    defaults: { _controller: GestionProjetBundle:Lots:updatelot }
    options:
        expose: true
        
gp_lot_delete:
    pattern: /delete-lot
    defaults: { _controller: GestionProjetBundle:Lots:deletelot }
    options:
        expose: true
        
gp_courier:
    pattern: /couriers
    defaults: { _controller: GestionProjetBundle:Couriers:couriers }
    options:
        expose: true
        
gp_courier_add:
    pattern: /add-courier
    defaults: { _controller: GestionProjetBundle:Courier:addcourier }
    options:
        expose: true

gp_courier_update:
    pattern: /update-courier
    defaults: { _controller: GestionProjetBundle:Courier:updatecourier }
    options:
        expose: true
        
gp_courier_delete:
    pattern: /delete-courier
    defaults: { _controller: GestionProjetBundle:Courier:deletecourier }
    options:
        expose: true