homepage:
    pattern: /
    defaults: { _controller: GestionProjetBundle:Default:index }
    options:
        expose: true

gp_header_projet_actif:
    pattern: /header-projet-actif
    defaults: { _controller: GestionProjetBundle:Projet:headerprojetactif }
    options:
        expose: true

gp_accueil:
    pattern: /accueil
    defaults: { _controller: GestionProjetBundle:Default:accueil }
    options:
        expose: true

gp_intervenants_accueil:
    pattern: /get-intervenants-accueil
    defaults: { _controller: GestionProjetBundle:Intervenant:getIntervenantsForAccueil }
    options:
        expose: true
        
gp_presentation_projet_accueil:
    pattern: /get-presentation-projet-accueil
    defaults: { _controller: GestionProjetBundle:Projet:getPresentationProjetAccueil }
    options:
        expose: true
        
gp_projet_admin:
    pattern: /projets-admin
    defaults: { _controller: GestionProjetBundle:Projet:projet }
    options:
        expose: true

gp_gestion_projet:
    pattern: /gestion-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:gestionprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_projet_add:
    pattern: /add-projet
    defaults: { _controller: GestionProjetBundle:Projet:addprojet }
    options:
        expose: true
        
gp_projet_update:
    pattern: /update-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:updateprojet }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_projet_get:
    pattern: /get-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:getprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_users_projet:
    pattern: /users-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:usersprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_intervenants_projet:
    pattern: /intervenants-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:intervenantsprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_user_projet_add:
    pattern: /add-user-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:adduserprojet }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_intervenant_projet_add:
    pattern: /add-intervenant-projet/{id}
    defaults: { _controller: GestionProjetBundle:Projet:addintervenantprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_user_projet_delete:
    pattern: /delete-user-projet/{idprojet}/{id} 
    defaults: { _controller: GestionProjetBundle:Projet:deleteuserprojet }
    requirements:
        id: \d+
        idprojet: \d+ 
    options:
        expose: true

gp_intervenant_projet_delete:
    pattern: /delete-intervenant-projet/{idprojet}/{id} 
    defaults: { _controller: GestionProjetBundle:Projet:deleteintervenantprojet }
    requirements:
        id: \d+
        idprojet: \d+ 
    options:
        expose: true

gp_projet_delete:
    pattern: /delete-projet/{id} 
    defaults: { _controller: GestionProjetBundle:Projet:deleteprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_intervenants_projet:
    pattern: /intervenants/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:intervenantsprojet }
    requirements:
        id: \d+
    options:
        expose: true

gp_intervenant:
    pattern: /intervenants
    defaults: { _controller: GestionProjetBundle:Intervenant:intervenants }
    options:
        expose: true
        
gp_intervenant_add:
    pattern: /add-intervenant
    defaults: { _controller: GestionProjetBundle:Intervenant:addintervenant }
    options:
        expose: true

gp_intervenant_update:
    pattern: /update-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:updateintervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_intervenant_get:
    pattern: /get-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:getintervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_intervenant_delete:
    pattern: /delete-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:deleteintervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_intervenant_details:
    pattern: /get-details-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:getdetailsintervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_evenement_update:
    pattern: /evenement/modifier/{id}
    defaults: { _controller: GestionProjetBundle:Calendar:updateEvenement }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_tache:
    pattern: /taches/{id}
    defaults: { _controller: GestionProjetBundle:Tache:taches }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_tache_add:
    pattern: /add-tache/{id}
    defaults: { _controller: GestionProjetBundle:Tache:addtache }
    requirements:
        id: \d+
    options:
        expose: true

gp_tache_update:
    pattern: /update-tache/{id}
    defaults: { _controller: GestionProjetBundle:Tache:updatetache }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_tache_get:
    pattern: /get-tache/{id}
    defaults: { _controller: GestionProjetBundle:Tache:gettache }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_tache_delete:
    pattern: /delete-tache/{id}
    defaults: { _controller: GestionProjetBundle:Tache:deletetache }
    requirements:
        id: \d+
    options:
        expose: true
    
gp_lot:
    pattern: /lots/{id}
    defaults: { _controller: GestionProjetBundle:Lot:lots }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_lot_add:
    pattern: /add-lot/{id}
    defaults: { _controller: GestionProjetBundle:Lot:addlot }
    requirements:
        id: \d+
    options:
        expose: true

gp_lot_update:
    pattern: /update-lot/{id}
    defaults: { _controller: GestionProjetBundle:Lot:updatelot }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_lot_get:
    pattern: /get-lot/{id}
    defaults: { _controller: GestionProjetBundle:Lot:getlot }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_lot_delete:
    pattern: /delete-lot/{id}
    defaults: { _controller: GestionProjetBundle:Lot:deletelot }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_courier:
    pattern: /courriers-envoyes/{id}
    defaults: { _controller: GestionProjetBundle:Courrier:couriersenvoyes }
    options:
        expose: true

gp_courier_recus:
    pattern: /courriers-recus/{id}
    defaults: { _controller: GestionProjetBundle:Courrier:couriersrecus }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_courier_add:
    pattern: /add-courrier/{id}
    defaults: { _controller: GestionProjetBundle:Courrier:addcourier }
    requirements:
        id: \d+
    options:
        expose: true

gp_courier_update:
    pattern: /update-courrier/{id}
    defaults: { _controller: GestionProjetBundle:Courrier:updatecourier }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_courier_get:
    pattern: /get-courier/{id}
    defaults: { _controller: GestionProjetBundle:Courrier:getcourier }
    options:
        expose: true
        
gp_courier_delete:
    pattern: /delete-courier
    defaults: { _controller: GestionProjetBundle:Courrier:deletecourier }
    options:
        expose: true
        
gp_evolution:
    pattern: /evolutions
    defaults: { _controller: GestionProjetBundle:Evolution:evolutions }
    options:
        expose: true
        
gp_evolution_intervenant_update:
    pattern: /update-evolution-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Evolution:updateevolution_intervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_evolution_intervenant_get:
    pattern: /get-evolution-intervenant/{id}
    defaults: { _controller: GestionProjetBundle:Evolution:getevolution_intervenant }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_evolution_projet_get:
    pattern: /get-evolution-projet/{id}
    defaults: { _controller: GestionProjetBundle:Evolution:getprojet_intervenant }
    requirements:
        id: \d+
    options:
        expose: true

gp_evolution_projet_update:
    pattern: /update-evolution-projet/{id}
    defaults: { _controller: GestionProjetBundle:Intervenant:updateevolution_projet }
    requirements:
        id: \d+
    options:
        expose: 
            
 
gp_photo:
    pattern: /photos/{id}
    defaults: { _controller: GestionProjetBundle:Photo:photos }
    options:
        expose: true


gp_galerie_photo:
    pattern: /galerie-photos
    defaults: { _controller: GestionProjetBundle:Photo:galeriephotos }
    options:
        expose: true
     

gp_photo_add:
    pattern: /add-photo/{id}
    defaults: { _controller: GestionProjetBundle:Photo:addphoto }
    requirements:
        id: \d+
    options:
        expose: true

gp_photo_update:
    pattern: /update-photo/{id}
    defaults: { _controller: GestionProjetBundle:Photo:updatephoto }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_photo_get:
    pattern: /get-photo/{id}
    defaults: { _controller: GestionProjetBundle:Photo:getphoto }
    requirements:
        id: \d+
    options:
        expose: true

gp_photo_details:
    pattern: /get-details-photo/{id}
    defaults: { _controller: GestionProjetBundle:Photo:getdetailsphoto }
    requirements:
        id: \d+
    options:
        expose: true
        
gp_photo_delete:
    pattern: /delete-photo/{id}
    defaults: { _controller: GestionProjetBundle:Photo:deletephoto }
    requirements:
        id: \d+
    options:
        expose: true
    