# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    user.authentication.handler.login_handler.class: UserBundle\Authentication\Handler\LoginHandler
    user.authentication.handler.logout_handler.class: UserBundle\Authentication\Handler\LogoutHandler

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user.authentication.handler.login_handler:
        class:  %user.authentication.handler.login_handler.class%
        arguments:  [@router, @security.context, @translator]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
             
    user.authentication.handler.logout_handler:
        class:  %user.authentication.handler.logout_handler.class%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
#    gestionprojetbundle.calendar_listener:
#         class: GestionProjetBundle\EventListener\CalendarEventListener
#         arguments: ["@doctrine.orm.entity_manager"]
#         tags:
#             - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents}